import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { GameProfile } from './gameTypes';
import { CompilerSettingsSnapshot } from './papyrusConfigTypes';

interface InteractiveCompileOptions {
  document: vscode.TextDocument;
  defaultGame: GameProfile;
  supportedGames: GameProfile[];
  getSettingsForGame: (game: GameProfile) => CompilerSettingsSnapshot;
  includeFlag: string;
  pathSeparator: string;
}

interface CompilerFlagDefinition {
  id: string;
  flag: string;
  label: string;
  description: string;
  detail?: string;
  requiresValue?: boolean;
  valueType?: 'string' | 'folder' | 'folders' | 'file' | 'saveFile';
  valuePrompt?: string;
  valuePlaceholder?: string;
  allowedGames?: GameProfile[];
  incompatibleWith?: string[];
  allowDuplicates?: boolean;
  formatValue?: (value: string, separators: { path: string }) => string;
  valueValidation?: (value: string) => string | undefined;
  iconId?: string;
}

interface SelectedFlag {
  id: string;
  rendered: string;
  definition: CompilerFlagDefinition | null;
  value?: string;
  source: 'existing' | 'user';
}

interface GamePickItem extends vscode.QuickPickItem {
  game: GameProfile;
}

interface ExistingArgumentsChoice extends vscode.QuickPickItem {
  value: 'keep' | 'discard';
}

interface RemovalPickItem extends vscode.QuickPickItem {
  flag: SelectedFlag;
}

interface ScriptPathPickItem extends vscode.QuickPickItem {
  action: 'done' | 'add' | 'restore' | 'remove';
  target?: string;
}

interface WorkingDirectoryPickItem extends vscode.QuickPickItem {
  action: 'use-current' | 'compiler' | 'script' | 'browse' | 'none';
}

interface FlagPickerItem extends vscode.QuickPickItem {
  action: 'definition' | 'custom' | 'remove' | 'finish';
  definition?: CompilerFlagDefinition;
}

interface CompilerPathPickItem extends vscode.QuickPickItem {
  action: 'use' | 'browse' | 'manual';
}

const FLAG_DEFINITIONS: CompilerFlagDefinition[] = [
  {
    id: 'optimize',
    flag: '-optimize',
    label: 'Enable optimizer (-optimize)',
    description: 'Run the Papyrus optimizer for better runtime performance.',
    detail: 'Recommended for release builds. Incompatible with -nooptimize.',
    incompatibleWith: ['nooptimize'],
    iconId: 'zap'
  },
  {
    id: 'nooptimize',
    flag: '-nooptimize',
    label: 'Disable optimizer (-nooptimize)',
    description: 'Skip Papyrus optimizer to aid debugging and retain exact source ordering.',
    detail: 'Only use when investigating compile issues. Incompatible with -optimize.',
    incompatibleWith: ['optimize'],
    iconId: 'debug'
  },
  {
    id: 'release',
    flag: '-release',
    label: 'Release build (-release)',
    description: 'Strip debug information and enforce optimized output.',
    detail: 'Use when shipping. Incompatible with -debug.',
    incompatibleWith: ['debug'],
    iconId: 'rocket'
  },
  {
    id: 'debug',
    flag: '-debug',
    label: 'Debug build (-debug)',
    description: 'Emit debug information for tracing and log output.',
    detail: 'Incompatible with -release. Expect slower scripts.',
    incompatibleWith: ['release'],
    iconId: 'bug'
  },
  {
    id: 'quiet',
    flag: '-quiet',
    label: 'Suppress output (-quiet)',
    description: 'Hide informational compiler output; show only warnings and errors.',
    iconId: 'mute'
  },
  {
    id: 'all',
    flag: '-all',
    label: 'Compile all scripts (-all)',
    description: 'Compile every .psc file found in the include paths before compiling the selected script.',
    iconId: 'list-unordered'
  },
  {
    id: 'asm',
    flag: '-asm',
    label: 'Emit assembly (-asm)',
    description: 'Generate additional .pas assembly output alongside compiled scripts.',
    detail: 'Useful for reviewing generated bytecode. Incompatible with -noasm.',
    incompatibleWith: ['noasm'],
    iconId: 'symbol-structure'
  },
  {
    id: 'noasm',
    flag: '-noasm',
    label: 'Skip assembly (-noasm)',
    description: 'Prevent .pas assembly files from being created.',
    detail: 'Incompatible with -asm.',
    incompatibleWith: ['asm'],
    iconId: 'eye-closed'
  },
  {
    id: 'import',
    flag: '-import',
    label: 'Additional import folders (-import)',
    description: 'Supply extra source folders for parent scripts and dependencies.',
    detail: 'Select one or more folders; the compiler searches them for missing dependencies.',
    requiresValue: true,
    valueType: 'folders',
    valuePrompt: 'Select additional folders that should be searched for Papyrus source files.',
    allowDuplicates: true,
    formatValue: (value) => `-import="${value}"`,
  iconId: 'library'
  },
  {
    id: 'include-path',
    flag: '-i',
    label: 'Extra include path (-i)',
    description: 'Append an extra include path for this compile beyond the configured script paths.',
    detail: 'Useful for temporary folders. You can add multiple include paths.',
    requiresValue: true,
    valueType: 'folder',
    valuePrompt: 'Select an additional include directory.',
    allowDuplicates: true,
    formatValue: (value) => `-i="${value}"`,
    iconId: 'folder-opened'
  },
  {
    id: 'output-dir',
    flag: '-o',
    label: 'Output directory (-o)',
    description: 'Override the compiler output directory for compiled .pex files.',
    requiresValue: true,
    valueType: 'folder',
    valuePrompt: 'Select a directory where compiled .pex files should be written.',
    valueValidation: value => !value.trim() ? 'Select or enter a directory.' : undefined,
    formatValue: (value) => `-o="${value}"`,
    iconId: 'file-directory'
  },
  {
    id: 'output-file',
    flag: '-op',
    label: 'Output file (-op)',
    description: 'Specify an explicit output path for the compiled script.',
    detail: 'Provide a .pex path. This overrides -o for the current script only.',
    requiresValue: true,
    valueType: 'saveFile',
    valuePrompt: 'Choose the .pex file path to generate.',
    formatValue: (value) => `-op="${value}"`,
    iconId: 'file-binary'
  },
  {
    id: 'flags-file',
    flag: '-flags',
    label: 'Flags file (-flags)',
    description: 'Load additional compiler flags from a text file.',
    detail: 'The file should contain one Papyrus compiler option per line.',
    requiresValue: true,
    valueType: 'file',
    valuePrompt: 'Select the flags text file to load.',
    formatValue: (value) => `-flags="${value}"`,
    iconId: 'file-text'
  },
  {
    id: 'sf-mode',
    flag: '-sf',
    label: 'Enable Starfield mode (-sf)',
    description: 'Enable Starfield compiler extensions such as struct support.',
    allowedGames: ['Starfield'],
    detail: 'Only applicable to Starfield scripts. Safe to omit for other games.',
    iconId: 'globe'
  }
];

const formatWithIcon = (iconId: string | undefined, label: string): string => {
  return iconId ? `$(${iconId}) ${label}` : label;
};

export async function runInteractiveCompile(options: InteractiveCompileOptions): Promise<void> {
  const selectedGame = await selectGameProfile(options);
  if (!selectedGame) {
    return;
  }

  const settings = options.getSettingsForGame(selectedGame);

  const compilerPath = await promptForCompilerPath(settings.compiler.path, selectedGame);
  if (!compilerPath) {
    return;
  }

  const scriptPaths = await promptForScriptPaths(settings.scriptPaths, selectedGame);
  if (!scriptPaths) {
    return;
  }

  const workingDirectory = await promptForWorkingDirectory(settings.compiler.cwd, compilerPath, options.document.uri.fsPath);
  if (workingDirectory === undefined) {
    // undefined indicates user cancelled.
    return;
  }

  const existingArgumentStrings = [...settings.compiler.args, ...settings.compiler.includeFlags];
  const initialFlagsResult = await gatherExistingArguments(existingArgumentStrings, selectedGame);
  if (!initialFlagsResult) {
    return;
  }

  const selectedFlags = await collectCompilerFlags(selectedGame, initialFlagsResult.selectedFlags, options.pathSeparator);
  if (!selectedFlags) {
    return;
  }

  const includeArgument = buildIncludeArgument(options.includeFlag, scriptPaths, options.pathSeparator);
  if (includeArgument) {
    selectedFlags.push({ id: `include#${Date.now()}`, rendered: includeArgument, definition: null, source: 'user' });
  }

  const finalArgs = selectedFlags.map(item => item.rendered);

  const cwdValue = workingDirectory ?? undefined;
  const workingDirectoryLabel = workingDirectory ?? '(terminal default)';

  // Use Start-Process to avoid PowerShell interpreting compiler flags as its own parameters
  const startProcessArgs = finalArgs.concat([options.document.uri.fsPath]).map(arg => `"${arg.replace(/"/g, '""')}"`).join(', ');
  const powershellCommand = `Start-Process -FilePath "${compilerPath.replace(/"/g, '""')}" -ArgumentList ${startProcessArgs} -NoNewWindow -Wait`;

  const summary = buildSummary({
    game: selectedGame,
    compilerPath,
    scriptPaths,
    workingDirectory: workingDirectoryLabel,
    flags: finalArgs,
    script: options.document.uri.fsPath
  });

  const confirm = await vscode.window.showInformationMessage(
    'Compile Papyrus script?',
    { modal: true, detail: summary },
    'Compile',
    'Cancel'
  );
  if (confirm !== 'Compile') {
    return;
  }

  const terminal = vscode.window.createTerminal({ name: `Papyrus Compile (${selectedGame})`, cwd: cwdValue });
  terminal.sendText(powershellCommand);
  terminal.show();

  vscode.window.showInformationMessage(`Papyrus: compiling ${path.basename(options.document.uri.fsPath)} using ${selectedGame} profile.`);
}

async function selectGameProfile(options: InteractiveCompileOptions): Promise<GameProfile | undefined> {
  const items: GamePickItem[] = options.supportedGames.map(game => {
    const settings = options.getSettingsForGame(game);
    const label = game === options.defaultGame ? `$(check) ${game}` : game;
    const compilerPath = settings.compiler.path ? settings.compiler.path : '(no compiler configured)';
    const details = scriptPathSummary(settings.scriptPaths);
    return {
      label,
      description: compilerPath,
      detail: `Script paths: ${details}`,
      game
    } satisfies GamePickItem;
  });

  const pick = await vscode.window.showQuickPick<GamePickItem>(items, {
    title: 'Papyrus Compile: Choose game profile',
    placeHolder: 'Select the game profile whose compiler and script paths should be used.'
  });

  return pick?.game;
}

async function promptForCompilerPath(initialPath: string, game: GameProfile): Promise<string | undefined> {
  let candidate = (initialPath || '').trim();

  while (true) {
    const items: CompilerPathPickItem[] = [];
    if (candidate) {
      items.push({
        label: formatWithIcon('check', `Use configured path (${candidate})`),
        description: fs.existsSync(candidate) ? 'File exists' : 'File not found',
        detail: 'Continue with the compiler path provided by the selected game profile.',
        action: 'use'
      } satisfies CompilerPathPickItem);
    }
    items.push({
      label: formatWithIcon('file-binary', 'Browse for PapyrusCompiler.exe'),
      description: 'Select the compiler executable from the file system.',
      action: 'browse'
    } satisfies CompilerPathPickItem);
    items.push({
      label: formatWithIcon('pencil', 'Enter path manually'),
      description: 'Type or paste the full path to PapyrusCompiler.exe.',
      action: 'manual'
    } satisfies CompilerPathPickItem);

    const selection = await vscode.window.showQuickPick<CompilerPathPickItem>(items, {
      title: `Papyrus Compile: Select compiler for ${game}`,
      placeHolder: 'Choose how you would like to provide the compiler executable.'
    });
    if (!selection) {
      return undefined;
    }

    if (selection.action === 'use') {
      const validation = validateCompilerPath(candidate);
      if (validation) {
        await vscode.window.showErrorMessage(validation);
        continue;
      }
      return path.normalize(candidate);
    }

    if (selection.action === 'browse') {
      const files = await vscode.window.showOpenDialog({
        canSelectFiles: true,
        canSelectFolders: false,
        canSelectMany: false,
        title: 'Select PapyrusCompiler.exe'
      });
      if (!files || files.length === 0) {
        continue;
      }
      const filePath = files[0].fsPath;
      const validation = validateCompilerPath(filePath);
      if (validation) {
        await vscode.window.showErrorMessage(validation);
        continue;
      }
      return path.normalize(filePath);
    }

    if (selection.action === 'manual') {
      const input = await vscode.window.showInputBox({
        title: 'Papyrus Compiler Path',
        value: candidate,
        prompt: 'Enter the full path to PapyrusCompiler.exe',
        validateInput: text => validateCompilerPath(text) ?? undefined
      });
      if (!input) {
        continue;
      }
      candidate = input.trim();
      return path.normalize(candidate);
    }
  }
}

async function promptForScriptPaths(initialPaths: string[], game: GameProfile): Promise<string[] | undefined> {
  let paths = dedupePaths(initialPaths);

  while (true) {
    const items: ScriptPathPickItem[] = [];
    if (paths.length) {
      for (const scriptPath of paths) {
        items.push({
          label: formatWithIcon('folder', scriptPath),
          description: 'Click to remove this folder from the include list.',
          action: 'remove',
          target: scriptPath
        } satisfies ScriptPathPickItem);
      }
    } else {
      items.push({
        label: formatWithIcon('info', 'No script folders configured'),
        description: 'Add at least one folder that contains .psc files before compiling.',
        action: 'add'
      } satisfies ScriptPathPickItem);
    }

    items.push({
      label: formatWithIcon('folder-opened', 'Add script folder'),
      description: 'Select one or more directories to add to the include search path.',
      action: 'add'
    } satisfies ScriptPathPickItem);

    if (initialPaths.length) {
      items.push({
        label: formatWithIcon('history', 'Restore profile defaults'),
        description: 'Revert to the script folders provided by the selected game profile.',
        action: 'restore'
      } satisfies ScriptPathPickItem);
    }

    items.push({
      label: formatWithIcon('check', 'Done'),
      description: 'Continue with the paths listed above.',
      action: 'done'
    } satisfies ScriptPathPickItem);

    const selection = await vscode.window.showQuickPick<ScriptPathPickItem>(items, {
      title: `Papyrus Compile: Script include folders (${game})`,
      placeHolder: 'Select a folder to remove it, or choose an action below.'
    });

    if (!selection) {
      return undefined;
    }

    if (selection.action === 'done') {
      return paths;
    }

    if (selection.action === 'restore') {
      paths = dedupePaths(initialPaths);
      continue;
    }

    if (selection.action === 'remove' && selection.target) {
      paths = paths.filter(p => !samePath(p, selection.target!));
      continue;
    }

    if (selection.action === 'add') {
      const folders = await vscode.window.showOpenDialog({
        canSelectFiles: false,
        canSelectFolders: true,
        canSelectMany: true,
        openLabel: 'Add script folder'
      });
      if (folders && folders.length > 0) {
        for (const folder of folders) {
          paths = ensurePath(paths, folder.fsPath);
        }
      }
      continue;
    }
  }
}

async function promptForWorkingDirectory(initialCwd: string, compilerPath: string, documentPath: string): Promise<string | undefined | null> {
  let current = (initialCwd || '').trim();

  while (true) {
    const compilerDir = path.dirname(compilerPath);
    const scriptDir = path.dirname(documentPath);
    const items: WorkingDirectoryPickItem[] = [];
    if (current) {
      items.push({
        label: formatWithIcon('home', `Use configured working directory (${current})`),
        description: fs.existsSync(current) ? 'Directory exists' : 'Directory not found',
        action: 'use-current'
      } satisfies WorkingDirectoryPickItem);
    }
    items.push({ label: formatWithIcon('tools', `Compiler directory (${compilerDir})`), description: 'Run the compiler from its own directory.', action: 'compiler' } satisfies WorkingDirectoryPickItem);
    items.push({ label: formatWithIcon('file-directory', `Script directory (${scriptDir})`), description: 'Run from the folder containing the current script.', action: 'script' } satisfies WorkingDirectoryPickItem);
    items.push({ label: formatWithIcon('folder-opened', 'Browse for directory'), description: 'Choose a custom working directory.', action: 'browse' } satisfies WorkingDirectoryPickItem);
    items.push({ label: formatWithIcon('circle-slash', 'No working directory (use terminal default)'), action: 'none' } satisfies WorkingDirectoryPickItem);

    const selection = await vscode.window.showQuickPick<WorkingDirectoryPickItem>(items, {
      title: 'Papyrus Compile: Working directory',
      placeHolder: 'Choose the working directory PapyrusCompiler.exe should run from.'
    });

    if (!selection) {
      return undefined;
    }

    if (selection.action === 'none') {
      return null;
    }

    if (selection.action === 'use-current') {
      const validation = validateDirectory(current);
      if (validation) {
        await vscode.window.showErrorMessage(validation);
        continue;
      }
      return path.normalize(current);
    }

    if (selection.action === 'compiler') {
      const validation = validateDirectory(compilerDir);
      if (validation) {
        await vscode.window.showErrorMessage(validation);
        continue;
      }
      return path.normalize(compilerDir);
    }

    if (selection.action === 'script') {
      const validation = validateDirectory(scriptDir);
      if (validation) {
        await vscode.window.showErrorMessage(validation);
        continue;
      }
      return path.normalize(scriptDir);
    }

    if (selection.action === 'browse') {
      const folders = await vscode.window.showOpenDialog({
        canSelectFiles: false,
        canSelectFolders: true,
        canSelectMany: false,
        openLabel: 'Select working directory'
      });
      if (!folders || folders.length === 0) {
        continue;
      }
      const folderPath = folders[0].fsPath;
      const validation = validateDirectory(folderPath);
      if (validation) {
        await vscode.window.showErrorMessage(validation);
        continue;
      }
      current = folderPath;
      return path.normalize(folderPath);
    }
  }
}

interface ExistingArgumentResult {
  selectedFlags: SelectedFlag[];
}

async function gatherExistingArguments(existingArgs: string[], game: GameProfile): Promise<ExistingArgumentResult | undefined> {
  if (existingArgs.length === 0) {
    return { selectedFlags: [] };
  }

  const preview = existingArgs.join(' ');
  const choice = await vscode.window.showQuickPick<ExistingArgumentsChoice>(
    [
      { label: formatWithIcon('check-all', 'Keep existing arguments'), description: preview, detail: 'Existing compiler arguments will be added. You can remove them later.', value: 'keep' },
      { label: formatWithIcon('trash', 'Discard existing arguments'), description: 'Start from a clean slate.', value: 'discard' }
    ],
    {
      title: 'Papyrus Compile: Existing arguments',
      placeHolder: 'Decide whether to keep the compiler arguments stored in settings.'
    }
  );

  if (!choice) {
    return undefined;
  }

  if (choice.value === 'discard') {
    return { selectedFlags: [] };
  }

  const selectedFlags: SelectedFlag[] = [];
  let counter = 0;
  for (const arg of existingArgs) {
  const parsed = parseArgument(arg, game);
    selectedFlags.push({
      id: parsed.definition ? `${parsed.definition.id}#existing${counter++}` : `custom#existing${counter++}`,
      rendered: parsed.rendered,
      definition: parsed.definition,
      value: parsed.value,
      source: 'existing'
    });
  }

  return { selectedFlags };
}

async function collectCompilerFlags(game: GameProfile, initialFlags: SelectedFlag[], pathSeparator: string): Promise<SelectedFlag[] | undefined> {
  const selected: SelectedFlag[] = [...initialFlags];
  let sequence = 0;

  while (true) {
    const availableDefs = FLAG_DEFINITIONS.filter(def => (!def.allowedGames || def.allowedGames.includes(game)) &&
      (def.allowDuplicates || !selected.some(sel => sel.definition?.id === def.id)) &&
      !isBlocked(def, selected));

    const items: FlagPickerItem[] = availableDefs.map(def => ({
      label: formatWithIcon(def.iconId ?? 'settings', def.label),
      description: def.description,
      detail: def.detail,
      action: 'definition',
      definition: def
    } satisfies FlagPickerItem));

    items.push({ label: formatWithIcon('add', 'Add custom argument'), description: 'Enter a raw compiler argument manually.', action: 'custom' } satisfies FlagPickerItem);

    if (selected.length) {
      items.push({ label: formatWithIcon('trash', 'Remove a selected argument'), description: 'Inspect and remove arguments that have been chosen.', action: 'remove' } satisfies FlagPickerItem);
    }

    items.push({ label: formatWithIcon('play', 'Run compiler'), description: 'Proceed with the currently selected arguments.', action: 'finish' } satisfies FlagPickerItem);

    const placeholder = selected.length
      ? `Selected: ${selected.map(flag => flag.rendered).join(' ')}. Choose an option below.`
      : 'No arguments selected yet. Choose an argument to add or finish to run the compiler.';

    const pick = await vscode.window.showQuickPick<FlagPickerItem>(items, {
      title: 'Papyrus Compile: Build argument list',
      placeHolder: placeholder
    });

    if (!pick) {
      return undefined;
    }

    if (pick.action === 'finish') {
      return selected;
    }

    if (pick.action === 'remove') {
      const removal = await vscode.window.showQuickPick<RemovalPickItem>(
        selected.map(flag => ({ label: formatWithIcon('trash', flag.rendered), description: flag.source === 'existing' ? 'From settings' : 'Added during this session', flag })),
        { title: 'Papyrus Compile: Remove argument', placeHolder: 'Select an argument to remove.' }
      );
      if (removal?.flag) {
        const index = selected.indexOf(removal.flag);
        if (index >= 0) {
          selected.splice(index, 1);
        }
      }
      continue;
    }

    if (pick.action === 'custom') {
      const custom = await vscode.window.showInputBox({
        title: 'Papyrus Compile: Custom argument',
        prompt: 'Enter the exact compiler argument to pass (e.g., -someSwitch="value").',
        validateInput: text => text.trim() ? undefined : 'Argument cannot be empty.'
      });
      if (!custom) {
        continue;
      }
      selected.push({
        id: `custom#${sequence++}`,
        rendered: custom.trim(),
        definition: null,
        source: 'user'
      });
      continue;
    }

    if (pick.action === 'definition' && pick.definition) {
      const rendered = await resolveFlagRendering(pick.definition, pathSeparator);
      if (!rendered) {
        continue;
      }
      selected.push({
        id: pick.definition.allowDuplicates ? `${pick.definition.id}#${sequence++}` : pick.definition.id,
        rendered,
        definition: pick.definition,
        source: 'user'
      });
    }
  }
}

async function resolveFlagRendering(definition: CompilerFlagDefinition, pathSeparator: string): Promise<string | undefined> {
  if (!definition.requiresValue) {
    return definition.flag;
  }

  const value = await promptForFlagValue(definition, pathSeparator);
  if (!value) {
    return undefined;
  }

  if (definition.formatValue) {
    return definition.formatValue(value, { path: pathSeparator });
  }

  return `${definition.flag}="${value}"`;
}

async function promptForFlagValue(definition: CompilerFlagDefinition, pathSeparator: string): Promise<string | undefined> {
  switch (definition.valueType) {
    case 'folder': {
      const selection = await vscode.window.showOpenDialog({
        canSelectFiles: false,
        canSelectFolders: true,
        canSelectMany: false,
        title: definition.valuePrompt || 'Select directory'
      });
      if (!selection || selection.length === 0) {
        return undefined;
      }
      const folderPath = selection[0].fsPath;
      if (definition.valueValidation) {
        const message = definition.valueValidation(folderPath);
        if (message) {
          await vscode.window.showErrorMessage(message);
          return undefined;
        }
      }
      return path.normalize(folderPath);
    }
    case 'folders': {
      const selection = await vscode.window.showOpenDialog({
        canSelectFiles: false,
        canSelectFolders: true,
        canSelectMany: true,
        title: definition.valuePrompt || 'Select directories'
      });
      if (!selection || selection.length === 0) {
        return undefined;
      }
      const folders = selection.map(uri => path.normalize(uri.fsPath));
      return folders.join(pathSeparator);
    }
    case 'file': {
      const selection = await vscode.window.showOpenDialog({
        canSelectFiles: true,
        canSelectFolders: false,
        canSelectMany: false,
        title: definition.valuePrompt || 'Select file'
      });
      if (!selection || selection.length === 0) {
        return undefined;
      }
      return path.normalize(selection[0].fsPath);
    }
    case 'saveFile': {
      const saveSelection = await vscode.window.showSaveDialog({
        title: definition.valuePrompt || 'Select output file'
      });
      if (!saveSelection) {
        return undefined;
      }
      return path.normalize(saveSelection.fsPath);
    }
    case 'string':
    default: {
      const input = await vscode.window.showInputBox({
        title: definition.valuePrompt || 'Enter value',
        placeHolder: definition.valuePlaceholder,
        validateInput: text => definition.valueValidation?.(text) ?? undefined
      });
      if (!input) {
        return undefined;
      }
      return input.trim();
    }
  }
}

function buildIncludeArgument(includeFlag: string, scriptPaths: string[], pathSeparator: string): string | undefined {
  if (!scriptPaths.length) {
    return undefined;
  }
  const joined = scriptPaths.join(pathSeparator);
  if (includeFlag.includes('=')) {
    return `${includeFlag}"${joined}"`;
  }
  return `${includeFlag}="${joined}"`;
}

function buildSummary(details: { game: GameProfile; compilerPath: string; scriptPaths: string[]; workingDirectory: string; flags: string[]; script: string }): string {
  const lines = [
    `Game profile: ${details.game}`,
    `Compiler: ${details.compilerPath}`,
    `Script: ${details.script}`,
    `Working directory: ${details.workingDirectory}`,
    `Script folders: ${details.scriptPaths.length ? details.scriptPaths.join(', ') : '(none)'}`,
    `Arguments: ${details.flags.length ? details.flags.join(' ') : '(none)'}`
  ];
  return lines.join('\n');
}

function scriptPathSummary(paths: string[]): string {
  if (!paths.length) {
    return '(none)';
  }
  if (paths.length === 1) {
    return paths[0];
  }
  return `${paths[0]} (+${paths.length - 1} more)`;
}

function validateCompilerPath(candidate: string): string | undefined {
  const trimmed = candidate.trim();
  if (!trimmed) {
    return 'Enter a path to PapyrusCompiler.exe.';
  }
  if (!fs.existsSync(trimmed)) {
    return 'The specified compiler path does not exist.';
  }
  if (!trimmed.toLowerCase().endsWith('.exe')) {
    return 'PapyrusCompiler.exe must be a Windows executable (.exe).';
  }
  if (!path.basename(trimmed).toLowerCase().includes('papyruscompiler')) {
    return 'The selected executable does not appear to be PapyrusCompiler.exe.';
  }
  return undefined;
}

function validateDirectory(directoryPath: string): string | undefined {
  if (!fs.existsSync(directoryPath)) {
    return 'The selected directory does not exist.';
  }
  if (!fs.statSync(directoryPath).isDirectory()) {
    return 'The selected path is not a directory.';
  }
  return undefined;
}

function parseArgument(argument: string, game: GameProfile): { rendered: string; definition: CompilerFlagDefinition | null; value?: string } {
  const trimmed = argument.trim();
  for (const definition of FLAG_DEFINITIONS) {
    if (definition.allowedGames && !definition.allowedGames.includes(game)) {
      continue;
    }
    if (definition.requiresValue) {
      if (trimmed.startsWith(definition.flag)) {
        const remainder = trimmed.slice(definition.flag.length).replace(/^=?"?/, '').replace(/"?$/, '');
        return { rendered: trimmed, definition, value: remainder };
      }
    } else if (trimmed === definition.flag) {
      return { rendered: trimmed, definition };
    }
  }
  return { rendered: trimmed, definition: null };
}

function isBlocked(definition: CompilerFlagDefinition, selected: SelectedFlag[]): boolean {
  if (!definition.incompatibleWith || definition.incompatibleWith.length === 0) {
    return false;
  }
  return selected.some(flag => {
    const def = flag.definition;
    if (!def) {
      return false;
    }
    return definition.incompatibleWith!.includes(def.id) || (def.incompatibleWith?.includes(definition.id) ?? false);
  });
}

function dedupePaths(paths: string[]): string[] {
  const result: string[] = [];
  for (const entry of paths) {
    if (!entry) {
      continue;
    }
    ensurePath(result, entry);
  }
  return result;
}

function ensurePath(list: string[], candidate: string): string[] {
  const normalized = path.normalize(candidate);
  if (!list.some(existing => samePath(existing, normalized))) {
    list.push(normalized);
  }
  return list;
}

function samePath(a: string, b: string): boolean {
  return path.normalize(a).toLowerCase() === path.normalize(b).toLowerCase();
}
